- block:

  - name: homebw cask packages installre
    community.general.homebrew_cask:
      name: "{{ item.name }}"
      state: 'installed'
      install_options: 'appdir=/Applications'
    with_items: '{{ packages }}'

  tags:
    - homebrew_cask
