taps:
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/cask-fonts
  - homebrew/core

packages:
  - { name: git, state: present }
  - { name: wget, state: present }
  - { name: vim, state: present }
  - { name: tree, state: present }
  - { name: nkf, state: present }
  - { name: rbenv, state: present }
  - { name: ruby-build, state: present }